import t2 from "@/public//Accommodation/a2.png";
import t3 from "@/public//Accommodation/a3.png";
import t1 from "@/public/Accommodation/a1.png";

export const accommodationsData = [
  // Apartments (5)
  {
    category: "Apartments",
    image: t1,
    location: "Beijing, China",
    flag: "/images/flags/cn.png",
    title: "Eclipse Haven Apartment",
    apartmentSlug: "eclipse-haven-apartment", // Added slug
    rating: 4.5,
    reviews: 120,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 3,
    bath: 2,
    price: "$378",
  },
  {
    category: "Apartments",
    image: t2,
    location: "Abu Dhabi, UAE",
    flag: "/images/flags/ae.png",
    title: "Emirates Pearl Towers",
    apartmentSlug: "emirates-pearl-towers", // Added slug
    rating: 4.8,
    reviews: 85,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 2,
    price: "$488",
  },
  {
    category: "Apartments",
    image: t3,
    location: "Washington, D.C., USA",
    flag: "/images/flags/us.png",
    title: "Capitol Heights Residences",
    apartmentSlug: "capitol-heights-residences", // Added slug
    rating: 4.5,
    reviews: 98,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 3,
    bath: 2,
    price: "$299",
  },
  {
    category: "Apartments",
    image: t2,
    location: "Lisbon, Portugal",
    flag: "/images/flags/pt.png",
    title: "Lisbon Central Loft",
    apartmentSlug: "lisbon-central-loft", // Added slug
    rating: 4.6,
    reviews: 77,
    cancellation: "Cancel within 48H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 1,
    price: "$310",
  },
  {
    category: "Apartments",
    image: t1,
    location: "Osaka, Japan",
    flag: "/images/flags/jp.png",
    title: "Osaka Urban Nest",
    apartmentSlug: "osaka-urban-nest", // Added slug
    rating: 4.7,
    reviews: 63,
    cancellation: "Cancel within 12H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 1,
    bath: 1,
    price: "$270",
  },

  // Hotels (5)
  {
    category: "Hotels",
    image: t3,
    location: "Paris, France",
    flag: "/images/flags/fr.png",
    title: "Grand Parisian Hotel",
    rating: 4.9,
    reviews: 210,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 2,
    price: "$520",
  },
  {
    category: "Hotels",
    image: t1,
    location: "London, UK",
    flag: "/images/flags/gb.png",
    title: "London Royal Palace",
    rating: 4.6,
    reviews: 134,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 2,
    price: "$489",
  },
  {
    category: "Hotels",
    image: t2,
    location: "Sydney, Australia",
    flag: "/images/flags/au.png",
    title: "Sydney Skyline Suites",
    rating: 4.7,
    reviews: 89,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 3,
    bath: 2,
    price: "$440",
  },
  {
    category: "Hotels",
    image: t3,
    location: "Rome, Italy",
    flag: "/images/flags/it.png",
    title: "Rome Regency Inn",
    rating: 4.4,
    reviews: 70,
    cancellation: "Cancel within 48H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 1,
    price: "$390",
  },
  {
    category: "Hotels",
    image: t2,
    location: "Cairo, Egypt",
    flag: "/images/flags/eg.png",
    title: "Cairo Desert Oasis",
    rating: 4.2,
    reviews: 55,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 1,
    price: "$280",
  },
];
