import t2 from "@/public//Accommodation/a2.png";
import t3 from "@/public//Accommodation/a3.png";
import t1 from "@/public/Accommodation/a1.png";

export const accommodationsData = [
  // Apartments (5)
  {
    category: "Apartments",
    image: t1,
    location: "Beijing, China",
    flag: "/images/flags/cn.png",
    title: "Eclipse Haven Apartment",
    apartmentSlug: "eclipse-haven-apartment",
    rating: 4.5,
    reviews: 120,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 3,
    bath: 2,
    price: "378",
    capacity: 6,
    size: "1200 ",
  },
  {
    category: "Apartments",
    image: t2,
    location: "Abu Dhabi, UAE",
    flag: "/images/flags/ae.png",
    title: "Emirates Pearl Towers",
    apartmentSlug: "emirates-pearl-towers",
    rating: 4.8,
    reviews: 85,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 2,
    price: "488",
    capacity: 4,
    size: "950 ",
  },
  {
    category: "Apartments",
    image: t3,
    location: "Washington, D.C., USA",
    flag: "/images/flags/us.png",
    title: "Capitol Heights Residences",
    apartmentSlug: "capitol-heights-residences",
    rating: 4.5,
    reviews: 98,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 3,
    bath: 2,
    price: "299",
    capacity: 5,
    size: "1100 ",
  },
  {
    category: "Apartments",
    image: t2,
    location: "Lisbon, Portugal",
    flag: "/images/flags/pt.png",
    title: "Lisbon Central Loft",
    apartmentSlug: "lisbon-central-loft",
    rating: 4.6,
    reviews: 77,
    cancellation: "Cancel within 48H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 1,
    price: "310",
    capacity: 3,
    size: "850 ",
  },
  {
    category: "Apartments",
    image: t1,
    location: "Osaka, Japan",
    flag: "/images/flags/jp.png",
    title: "Osaka Urban Nest",
    apartmentSlug: "osaka-urban-nest",
    rating: 4.7,
    reviews: 63,
    cancellation: "Cancel within 12H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 1,
    bath: 1,
    price: "270",
    capacity: 2,
    size: "600 ",
  },

  // Hotels (5)
  {
    category: "Hotels",
    image: t3,
    location: "Paris, France",
    flag: "/images/flags/fr.png",
    title: "Grand Parisian Hotel",
    rating: 4.9,
    reviews: 210,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 2,
    price: "520",
    capacity: 4,
    size: "500 ",
  },
  {
    category: "Hotels",
    image: t1,
    location: "London, UK",
    flag: "/images/flags/gb.png",
    title: "London Royal Palace",
    rating: 4.6,
    reviews: 134,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 2,
    price: "489",
    capacity: 4,
    size: "520 ",
  },
  {
    category: "Hotels",
    image: t2,
    location: "Sydney, Australia",
    flag: "/images/flags/au.png",
    title: "Sydney Skyline Suites",
    rating: 4.7,
    reviews: 89,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 3,
    bath: 2,
    price: "440",
    capacity: 6,
    size: "700 ",
  },
  {
    category: "Hotels",
    image: t3,
    location: "Rome, Italy",
    flag: "/images/flags/it.png",
    title: "Rome Regency Inn",
    rating: 4.4,
    reviews: 70,
    cancellation: "Cancel within 48H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 1,
    price: "390",
    capacity: 3,
    size: "450 ",
  },
  {
    category: "Hotels",
    image: t2,
    location: "Cairo, Egypt",
    flag: "/images/flags/eg.png",
    title: "Cairo Desert Oasis",
    rating: 4.2,
    reviews: 55,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 1,
    price: "280",
    capacity: 3,
    size: "430 ",
  },
];
