export const adminUsers = [
  {
    id: "#331787",
    name: "Chris Lee",
    email: "chris.lee@gmail.com",
    phone: "(907) 555-1006",
    role: "Guest",
    joinDate: "08/01/2025",
    status: "Inactive",
    profileImage: "/usericon/avatar.png",
    verificationStatus: {
      status: "Pending verification",
      rating: 3.6,
    },
    contact: {
      email: "chris.lee@gmail.com",
      phone: "(907) 555-1006",
      address: "8 12 Victoria Road Barnsley, South Yorkshire S70 2BB",
    },
    bio: "Described by Queenstown House & Garden magazine...",
    details: {
      joinDate: "08/01/2025",
      gender: "Not specified",
      dateOfBirth: "Not specified",
      language: "English",
      lastActive: "05/17/2025",
    },
  },
  {
    id: "#331790",
    name: "David Thomas",
    email: "david.thomas@gmail.com",
    phone: "(907) 555-1010",
    role: "Admin",
    joinDate: "08/01/2025",
    status: "Inactive",
    profileImage: "/usericon/avatar.png",
    verificationStatus: {
      status: "Pending verification",
      rating: 4.1,
    },
    contact: {
      email: "david.thomas@gmail.com",
      phone: "(907) 555-1010",
      address: "8 12 Victoria Road Barnsley, South Yorkshire S70 2BB",
    },
    bio: "Described by Queenstown House & Garden magazine...",
    details: {
      joinDate: "08/01/2025",
      gender: "Not specified",
      dateOfBirth: "Not specified",
      language: "English",
      lastActive: "05/17/2025",
    },
  },
  {
    id: "#331791",
    name: "Susan Jackson",
    email: "susan.jackson@gmail.com",
    phone: "(907) 555-1011",
    role: "User",
    joinDate: "08/01/2025",
    status: "Pending",
    profileImage: "/usericon/avatar.png",
    verificationStatus: {
      status: "Pending verification",
      rating: 3.9,
    },
    contact: {
      email: "susan.jackson@gmail.com",
      phone: "(907) 555-1011",
      address: "8 12 Victoria Road Barnsley, South Yorkshire S70 2BB",
    },
    bio: "Described by Queenstown House & Garden magazine...",
    details: {
      joinDate: "08/01/2025",
      gender: "Not specified",
      dateOfBirth: "Not specified",
      language: "English",
      lastActive: "05/17/2025",
    },
  },
  {
    id: "#331792",
    name: "Joseph White",
    email: "joseph.white@gmail.com",
    phone: "(907) 555-1012",
    role: "Host",
    joinDate: "08/01/2025",
    status: "Active",
    profileImage: "/usericon/avatar.png",
    verificationStatus: {
      status: "Pending verification",
      rating: 4.6,
    },
    contact: {
      email: "joseph.white@gmail.com",
      phone: "(907) 555-1012",
      address: "8 12 Victoria Road Barnsley, South Yorkshire S70 2BB",
    },
    bio: "Described by Queenstown House & Garden magazine...",
    details: {
      joinDate: "08/01/2025",
      gender: "Not specified",
      dateOfBirth: "Not specified",
      language: "English",
      lastActive: "05/17/2025",
    },
  },
  {
    id: "#331793",
    name: "Sarah Harris",
    email: "sarah.harris@gmail.com",
    phone: "(907) 555-1013",
    role: "Admin",
    joinDate: "08/01/2025",
    status: "Pending",
    profileImage: "/usericon/avatar.png",
    verificationStatus: {
      status: "Pending verification",
      rating: 4.4,
    },
    contact: {
      email: "sarah.harris@gmail.com",
      phone: "(907) 555-1013",
      address: "8 12 Victoria Road Barnsley, South Yorkshire S70 2BB",
    },
    bio: "Described by Queenstown House & Garden magazine...",
    details: {
      joinDate: "08/01/2025",
      gender: "Not specified",
      dateOfBirth: "Not specified",
      language: "English",
      lastActive: "05/17/2025",
    },
  },
];
