export const adminUsers = [
  {
    id: "#123562",
    name: "Elisabeth Sarah",
    email: "elisabeth-sarah@gmail.com",
    number: "(217) 555-0113",
    role: "Guest",
    joinDate: "2025-01-25",
    status: "Active",
    gender: "Female",
    dob: "1995-06-15",
    language: "English",
    lastActive: "2025-02-01",
    verified: false,
    rating: 4.7,
    address: "8 12 Victoria Road Barnsley, South Yorkshire S70 2BB",
    description:
      "Described by Queenstown House & Garden magazine as having one of the best views we’ve ever seen’ you will love relaxing in this newly built",
  },
  {
    id: "#123543",
    name: "Kristin Watson",
    email: "kristin-watson@gmail.com",
    number: "(225) 555-0118",
    role: "Host",
    joinDate: "2025-01-25",
    status: "Active",
    gender: "Male",
    dob: "1990-07-15",
    language: "English",
    lastActive: "2025-02-01",
    verified: true,
    rating: 4.7,
    address: "1406 Mattson Street, Astoria, OR 97103",
    description:
      "Described by Queenstown House & Garden magazine as having one of the best views we’ve ever seen’ you will love relaxing in this newly built",
    stats: {
      property: 3,
      tour: 2,
      servedGuests: 248,
    },
  },
  {
    id: "#123544",
    name: "Ronald Richards",
    email: "ronald.richards@example.com",
    number: "(702) 555-0122",
    role: "Host",
    joinDate: "2025-12-01",
    status: "Active",
    gender: "Male",
    dob: "1985-04-10",
    language: "English",
    lastActive: "2025-02-03",
    verified: true,
    rating: 4.9,
    address: "789 Sunset Blvd, Las Vegas, NV 89101",
    description:
      "With over 10 properties across Nevada, Ronald offers top-tier hospitality for city travelers.",
    stats: {
      property: 10,
      tour: 5,
      servedGuests: 1345,
    },
  },
  {
    id: "#123545",
    name: "Wade Warren",
    email: "wade.warren@example.com",
    number: "(208) 555-0112",
    role: "Guest",
    joinDate: "2025-01-02",
    status: "Active",
    gender: "Male",
    dob: "1992-11-09",
    language: "English",
    lastActive: "2025-01-29",
    verified: false,
    rating: 4.3,
    address: "22 Creekside Road, Boise, ID 83702",
    description:
      "A frequent traveler with a love for countryside stays and garden views.",
  },
  {
    id: "#123546",
    name: "Eleanor Pena",
    email: "eleanor.pena@example.com",
    number: "(870) 555-0110",
    role: "Guest",
    joinDate: "2025-02-01",
    status: "Inactive",
    gender: "Female",
    dob: "1988-09-30",
    language: "English",
    lastActive: "2025-02-10",
    verified: false,
    rating: 3.9,
    address: "45 Pine Lane, Little Rock, AR 72201",
    description:
      "Enjoys scenic views and rustic hideaways for weekend getaways.",
  },
  {
    id: "#123547",
    name: "Darrel Steward",
    email: "darrel.steward@example.com",
    number: "(252) 555-0126",
    role: "Guest",
    joinDate: "2025-08-01",
    status: "Banned",
    gender: "Male",
    dob: "1991-01-12",
    language: "English",
    lastActive: "2025-08-10",
    verified: false,
    rating: 2.5,
    address: "5 Maple Street, Raleigh, NC 27601",
    description:
      "Account suspended due to repeated policy violations during stays.",
  },
  {
    id: "#123548",
    name: "Henry Gosh",
    email: "henry.gosh@example.com",
    number: "(817) 555-0132",
    role: "Host",
    joinDate: "2025-08-01",
    status: "Active",
    gender: "Male",
    dob: "1987-12-21",
    language: "English",
    lastActive: "2025-08-11",
    verified: true,
    rating: 4.8,
    address: "11 Oak Avenue, Austin, TX 73301",
    description:
      "Known for luxury apartments and seamless guest experiences in Texas.",
    stats: {
      property: 6,
      tour: 4,
      servedGuests: 780,
    },
  },
  {
    id: "#123549",
    name: "Esther Howard",
    email: "esther.howard@example.com",
    number: "(702) 555-0122",
    role: "Host",
    joinDate: "2025-08-01",
    status: "Active",
    gender: "Female",
    dob: "1993-05-08",
    language: "English",
    lastActive: "2025-08-12",
    verified: true,
    rating: 4.6,
    address: "2 Magnolia Blvd, Henderson, NV 89002",
    description:
      "Esther’s properties feature spa-like amenities and high guest ratings.",
    stats: {
      property: 4,
      tour: 1,
      servedGuests: 390,
    },
  },
  {
    id: "#123550",
    name: "Dianne Russel",
    email: "dianne.russel@example.com",
    number: "(603) 555-0125",
    role: "Guest",
    joinDate: "2025-08-01",
    status: "Active",
    gender: "Female",
    dob: "1996-08-22",
    language: "English",
    lastActive: "2025-08-14",
    verified: true,
    rating: 4.4,
    address: "90 Birch Hollow Dr, Concord, NH 03301",
    description:
      "Always leaves glowing reviews and maintains great guest conduct.",
  },
  {
    id: "#123551",
    name: "Theresa Webb",
    email: "theresa.webb@example.com",
    number: "(307) 555-0101",
    role: "Host",
    joinDate: "2025-08-01",
    status: "Active",
    gender: "Female",
    dob: "1989-02-03",
    language: "English",
    lastActive: "2025-08-15",
    verified: true,
    rating: 4.9,
    address: "171 Sunrise Hill, Cheyenne, WY 82001",
    description:
      "Specializes in serene mountain lodges and eco-friendly stays.",
    stats: {
      property: 5,
      tour: 3,
      servedGuests: 652,
    },
  },
];
