import t1 from "@/public/hotel/h1.jpg";
import t2 from "@/public/hotel/h2.jpg";
import { default as t3, default as t6 } from "@/public/hotel/h3.jpg";
import t4 from "@/public/hotel/h4.jpg";
import t5 from "@/public/hotel/h5.jpg";

export const hotelData = [
  // Apartments (5)
  {
    category: "Apartments",
    image: t1,
    location: "Beijing, China",
    flag: "/images/flags/cn.png",
    title: "Beijing Hotel",
    hotelSlug: "beijing-hotel",
    rating: 4.5,
    reviews: 120,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 3,
    bath: 2,
    price: "$378",
  },
  {
    category: "Apartments",
    image: t2,
    location: "Abu Dhabi, UAE",
    flag: "/images/flags/ae.png",
    title: "Abu Dhabi Hotel",
    hotelSlug: "abu-dhabi-hotel",
    rating: 4.8,
    reviews: 85,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 2,
    price: "$488",
  },
  {
    category: "Apartments",
    image: t3,
    location: "Washington, D.C., USA",
    flag: "/images/flags/us.png",
    title: "Washington, D.C. Hotel",
    hotelSlug: "washington-dc-hotel",
    rating: 4.5,
    reviews: 98,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 3,
    bath: 2,
    price: "$299",
  },
  {
    category: "Apartments",
    image: t4,
    location: "Lisbon, Portugal",
    flag: "/images/flags/pt.png",
    title: "Lisbon Hotel",
    hotelSlug: "lisbon-hotel",
    rating: 4.6,
    reviews: 77,
    cancellation: "Cancel within 48H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 1,
    price: "$310",
  },
  {
    category: "Apartments",
    image: t5,
    location: "Osaka, Japan",
    flag: "/images/flags/jp.png",
    title: "Osaka Hotel",
    hotelSlug: "osaka-hotel",
    rating: 4.7,
    reviews: 63,
    cancellation: "Cancel within 12H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 1,
    bath: 1,
    price: "$270",
  },

  // Hotels (5)
  {
    category: "Hotels",
    image: t6,
    location: "Paris, France",
    flag: "/images/flags/fr.png",
    title: "Paris Hotel",
    hotelSlug: "paris-hotel",
    rating: 4.9,
    reviews: 210,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 2,
    price: "$520",
  },
  {
    category: "Hotels",
    image: t2,
    location: "London, UK",
    flag: "/images/flags/gb.png",
    title: "London Hotel",
    hotelSlug: "london-hotel",
    rating: 4.6,
    reviews: 134,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 2,
    price: "$489",
  },
  {
    category: "Hotels",
    image: t3,
    location: "Sydney, Australia",
    flag: "/images/flags/au.png",
    title: "Sydney Hotel",
    hotelSlug: "sydney-hotel",
    rating: 4.7,
    reviews: 89,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 3,
    bath: 2,
    price: "$440",
  },
  {
    category: "Hotels",
    image: t1,
    location: "Rome, Italy",
    flag: "/images/flags/it.png",
    title: "Rome Hotel",
    hotelSlug: "rome-hotel",
    rating: 4.4,
    reviews: 70,
    cancellation: "Cancel within 48H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 1,
    price: "$390",
  },
  {
    category: "Hotels",
    image: t6,
    location: "Cairo, Egypt",
    flag: "/images/flags/eg.png",
    title: "Cairo Hotel",
    hotelSlug: "cairo-hotel",
    rating: 4.2,
    reviews: 55,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 1,
    price: "$280",
  },
  {
    category: "Apartments",
    image: t2,
    location: "Abu Dhabi, UAE",
    flag: "/images/flags/ae.png",
    title: "Abu Dhabi Hotel",
    hotelSlug: "abu-dhabi-hotel",
    rating: 4.8,
    reviews: 85,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 2,
    price: "$488",
  },
  {
    category: "Apartments",
    image: t3,
    location: "Washington, D.C., USA",
    flag: "/images/flags/us.png",
    title: "Washington, D.C. Hotel",
    hotelSlug: "washington-dc-hotel",
    rating: 4.5,
    reviews: 98,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 3,
    bath: 2,
    price: "$299",
  },
  {
    category: "Apartments",
    image: t4,
    location: "Lisbon, Portugal",
    flag: "/images/flags/pt.png",
    title: "Lisbon Hotel",
    hotelSlug: "lisbon-hotel",
    rating: 4.6,
    reviews: 77,
    cancellation: "Cancel within 48H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 1,
    price: "$310",
  },
  {
    category: "Apartments",
    image: t5,
    location: "Osaka, Japan",
    flag: "/images/flags/jp.png",
    title: "Osaka Hotel",
    hotelSlug: "osaka-hotel",
    rating: 4.7,
    reviews: 63,
    cancellation: "Cancel within 12H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 1,
    bath: 1,
    price: "$270",
  },

  // Hotels (5)
  {
    category: "Hotels",
    image: t6,
    location: "Paris, France",
    flag: "/images/flags/fr.png",
    title: "Paris Hotel",
    hotelSlug: "paris-hotel",
    rating: 4.9,
    reviews: 210,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 2,
    price: "$520",
  },
  {
    category: "Hotels",
    image: t2,
    location: "London, UK",
    flag: "/images/flags/gb.png",
    title: "London Hotel",
    hotelSlug: "london-hotel",
    rating: 4.6,
    reviews: 134,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 2,
    price: "$489",
  },
  {
    category: "Hotels",
    image: t3,
    location: "Sydney, Australia",
    flag: "/images/flags/au.png",
    title: "Sydney Hotel",
    hotelSlug: "sydney-hotel",
    rating: 4.7,
    reviews: 89,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 3,
    bath: 2,
    price: "$440",
  },
  {
    category: "Hotels",
    image: t1,
    location: "Rome, Italy",
    flag: "/images/flags/it.png",
    title: "Rome Hotel",
    hotelSlug: "rome-hotel",
    rating: 4.4,
    reviews: 70,
    cancellation: "Cancel within 48H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 1,
    price: "$390",
  },
  {
    category: "Hotels",
    image: t6,
    location: "Cairo, Egypt",
    flag: "/images/flags/eg.png",
    title: "Cairo Hotel",
    hotelSlug: "cairo-hotel",
    rating: 4.2,
    reviews: 55,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 1,
    price: "$280",
  },
  {
    category: "Apartments",
    image: t2,
    location: "Abu Dhabi, UAE",
    flag: "/images/flags/ae.png",
    title: "Abu Dhabi Hotel",
    hotelSlug: "abu-dhabi-hotel",
    rating: 4.8,
    reviews: 85,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 2,
    price: "$488",
  },
  {
    category: "Apartments",
    image: t3,
    location: "Washington, D.C., USA",
    flag: "/images/flags/us.png",
    title: "Washington, D.C. Hotel",
    hotelSlug: "washington-dc-hotel",
    rating: 4.5,
    reviews: 98,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 3,
    bath: 2,
    price: "$299",
  },
  {
    category: "Apartments",
    image: t4,
    location: "Lisbon, Portugal",
    flag: "/images/flags/pt.png",
    title: "Lisbon Hotel",
    hotelSlug: "lisbon-hotel",
    rating: 4.6,
    reviews: 77,
    cancellation: "Cancel within 48H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 1,
    price: "$310",
  },
  {
    category: "Apartments",
    image: t5,
    location: "Osaka, Japan",
    flag: "/images/flags/jp.png",
    title: "Osaka Hotel",
    hotelSlug: "osaka-hotel",
    rating: 4.7,
    reviews: 63,
    cancellation: "Cancel within 12H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 1,
    bath: 1,
    price: "$270",
  },

  // Hotels (5)
  {
    category: "Hotels",
    image: t6,
    location: "Paris, France",
    flag: "/images/flags/fr.png",
    title: "Paris Hotel",
    hotelSlug: "paris-hotel",
    rating: 4.9,
    reviews: 210,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 2,
    price: "$520",
  },
  {
    category: "Hotels",
    image: t2,
    location: "London, UK",
    flag: "/images/flags/gb.png",
    title: "London Hotel",
    hotelSlug: "london-hotel",
    rating: 4.6,
    reviews: 134,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 2,
    price: "$489",
  },
  {
    category: "Hotels",
    image: t3,
    location: "Sydney, Australia",
    flag: "/images/flags/au.png",
    title: "Sydney Hotel",
    hotelSlug: "sydney-hotel",
    rating: 4.7,
    reviews: 89,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 3,
    bath: 2,
    price: "$440",
  },
  {
    category: "Hotels",
    image: t1,
    location: "Rome, Italy",
    flag: "/images/flags/it.png",
    title: "Rome Hotel",
    hotelSlug: "rome-hotel",
    rating: 4.4,
    reviews: 70,
    cancellation: "Cancel within 48H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 1,
    price: "$390",
  },
  {
    category: "Hotels",
    image: t6,
    location: "Cairo, Egypt",
    flag: "/images/flags/eg.png",
    title: "Cairo Hotel",
    hotelSlug: "cairo-hotel",
    rating: 4.2,
    reviews: 55,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 1,
    price: "$280",
  },
];
