import b1 from "@/public/toure/t1.jpg";
import b2 from "@/public/toure/t2.jpg";
import b3 from "@/public/toure/t3.jpg";
import b4 from "@/public/toure/t4.jpg";
import b5 from "@/public/toure/t5.jpg";
export const listingData = [
  {
    userId: "#0001",
    propertyName: "Eclipse Haven",
    type: "Apartment",
    location: "Abu Dhabi, UAE",
    price: 4999,
    joinDate: "Feb 6, 2022",
    status: "Available",
    image: b1,
    rating: 4.7,
    tourDetails: {
      duration: "3 days",
      groupSize: "12 people",
      inclusive: "Hotel + All Included",
      location: "Kathmandu, Nepal",
    },
  },
  {
    userId: "#0002",
    propertyName: "The Greenbrier",
    type: "Tour",
    location: "Beijing, China",
    price: 4999,
    joinDate: "Jan 8, 2025",
    status: "Available",
    image: b2,
    rating: 4.8,
    tourDetails: {
      duration: "7 days",
      groupSize: "25 people",
      inclusive: "Flights + Hotel",
      location: "Beijing, China",
    },
  },
  {
    userId: "#0003",
    propertyName: "Lakeside Luxe Flats",
    type: "Apartment",
    location: "Abu Dhabi, UAE",
    price: 3999,
    joinDate: "April 18, 2022",
    status: "Cancel",
    image: b3,
    rating: 4.5,
    tourDetails: {
      duration: "5 days",
      groupSize: "8 people",
      inclusive: "Hotel + All Included",
      location: "Abu Dhabi, UAE",
    },
  },
  {
    userId: "#0004",
    propertyName: "The Sapphire Haven",
    type: "Apartment",
    location: "Abu Dhabi, UAE",
    price: 2400,
    joinDate: "May 22, 2022",
    status: "Available",
    image: b4,
    rating: 4.3,
    tourDetails: {
      duration: "4 days",
      groupSize: "15 people",
      inclusive: "Hotel + All Included",
      location: "Abu Dhabi, UAE",
    },
  },
  {
    userId: "#0005",
    propertyName: "Mandarin Oriental",
    type: "Hotel",
    location: "Abu Dhabi, UAE",
    price: 4999,
    joinDate: "Feb 6, 2022",
    status: "Booked",
    image: b5,
    rating: 4.7,
    tourDetails: {
      duration: "3 days",
      groupSize: "10 people",
      inclusive: "Hotel + Meals",
      location: "Abu Dhabi, UAE",
    },
  },
  {
    userId: "#0006",
    propertyName: "Summit View",
    type: "Apartment",
    location: "New York, USA",
    price: 3500,
    joinDate: "March 11, 2023",
    status: "Cancel",
    image: b1,
    rating: 4.2,
    tourDetails: {
      duration: "4 days",
      groupSize: "5 people",
      inclusive: "Hotel + City Tour",
      location: "New York, USA",
    },
  },
  {
    userId: "#0007",
    propertyName: "Aurora Heights",
    type: "Apartment",
    location: "Los Angeles, USA",
    price: 3000,
    joinDate: "Aug 14, 2023",
    status: "Available",
    image: b2,
    rating: 4.4,
    tourDetails: {
      duration: "5 days",
      groupSize: "10 people",
      inclusive: "Hotel + All Included",
      location: "Los Angeles, USA",
    },
  },
  {
    userId: "#0008",
    propertyName: "The Knickerbocker",
    type: "Hotel",
    location: "New York, USA",
    price: 3500,
    joinDate: "Sept 21, 2022",
    status: "Cancel",
    image: b3,
    rating: 4.6,
    tourDetails: {
      duration: "6 days",
      groupSize: "20 people",
      inclusive: "Meals + City Tour",
      location: "New York, USA",
    },
  },
  {
    userId: "#0009",
    propertyName: "Italy Awaits",
    type: "Tour",
    location: "Rome, Italy",
    price: 6000,
    joinDate: "May 22, 2023",
    status: "Available",
    image: b4,
    rating: 4.9,
    tourDetails: {
      duration: "10 days",
      groupSize: "30 people",
      inclusive: "Flights + Hotel + Meals",
      location: "Rome, Italy",
    },
  },
  {
    userId: "#0010",
    propertyName: "The Beverly Hills",
    type: "Hotel",
    location: "California, USA",
    price: 4500,
    joinDate: "March 5, 2023",
    status: "Cancel",
    image: b5,
    rating: 4.8,
    tourDetails: {
      duration: "4 days",
      groupSize: "10 people",
      inclusive: "Hotel + Breakfast",
      location: "California, USA",
    },
  },
  {
    userId: "#0011",
    propertyName: "Indonesia Unveiled",
    type: "Tour",
    location: "Bali, Indonesia",
    price: 5500,
    joinDate: "Feb 12, 2023",
    status: "Booked",
    image: b1,
    rating: 4.6,
    tourDetails: {
      duration: "8 days",
      groupSize: "18 people",
      inclusive: "Hotel + All Included",
      location: "Bali, Indonesia",
    },
  },
  {
    userId: "#0012",
    propertyName: "The Plaza",
    type: "Hotel",
    location: "New York, USA",
    price: 6000,
    joinDate: "Sept 5, 2022",
    status: "Available",
    image: b2,
    rating: 4.7,
    tourDetails: {
      duration: "3 days",
      groupSize: "8 people",
      inclusive: "Hotel + Meals",
      location: "New York, USA",
    },
  },
  {
    userId: "#0013",
    propertyName: "Grand Hills Resort",
    type: "Apartment",
    location: "Miami, USA",
    price: 4500,
    joinDate: "Jan 15, 2023",
    status: "Booked",
    image: b3,
    rating: 4.8,
    tourDetails: {
      duration: "5 days",
      groupSize: "10 people",
      inclusive: "Hotel + Beach Access",
      location: "Miami, USA",
    },
  },
  {
    userId: "#0014",
    propertyName: "Sunset Villa",
    type: "Hotel",
    location: "Hawaii, USA",
    price: 5200,
    joinDate: "April 10, 2023",
    status: "Available",
    image: b4,
    rating: 4.9,
    tourDetails: {
      duration: "6 days",
      groupSize: "15 people",
      inclusive: "Hotel + All Meals",
      location: "Hawaii, USA",
    },
  },
  {
    userId: "#0015",
    propertyName: "Luxury Escape",
    type: "Tour",
    location: "Paris, France",
    price: 4500,
    joinDate: "Feb 7, 2023",
    status: "Available",
    image: b1,
    rating: 4.5,
    tourDetails: {
      duration: "7 days",
      groupSize: "20 people",
      inclusive: "Flights + Hotel + Meals",
      location: "Paris, France",
    },
  },
  {
    userId: "#0016",
    propertyName: "Oceanview Paradise",
    type: "Apartment",
    location: "Maldives",
    price: 6500,
    joinDate: "May 1, 2022",
    status: "Booked",
    image: b5,
    rating: 4.8,
    tourDetails: {
      duration: "5 days",
      groupSize: "8 people",
      inclusive: "Hotel + Spa Access",
      location: "Maldives",
    },
  },
  {
    userId: "#0017",
    propertyName: "Mountain Retreat",
    type: "Hotel",
    location: "Colorado, USA",
    price: 3500,
    joinDate: "Oct 13, 2023",
    status: "Available",
    image: b1,
    rating: 4.7,
    tourDetails: {
      duration: "4 days",
      groupSize: "12 people",
      inclusive: "Hotel + Meals",
      location: "Colorado, USA",
    },
  },
  {
    userId: "#0018",
    propertyName: "Tropical Getaway",
    type: "Tour",
    location: "Bora Bora",
    price: 7000,
    joinDate: "May 3, 2023",
    status: "Booked",
    image: b2,
    rating: 5.0,
    tourDetails: {
      duration: "10 days",
      groupSize: "25 people",
      inclusive: "Hotel + Flights + Meals",
      location: "Bora Bora",
    },
  },
  {
    userId: "#0019",
    propertyName: "Desert Oasis",
    type: "Apartment",
    location: "Dubai, UAE",
    price: 5000,
    joinDate: "Jan 22, 2024",
    status: "Available",
    image: b3,
    rating: 4.6,
    tourDetails: {
      duration: "6 days",
      groupSize: "10 people",
      inclusive: "Hotel + All Meals",
      location: "Dubai, UAE",
    },
  },
  {
    userId: "#0020",
    propertyName: "Snowy Peaks Lodge",
    type: "Hotel",
    location: "Aspen, USA",
    price: 4500,
    joinDate: "Dec 5, 2023",
    status: "Booked",
    image: b4,
    rating: 4.9,
    tourDetails: {
      duration: "5 days",
      groupSize: "8 people",
      inclusive: "Hotel + Ski Pass",
      location: "Aspen, USA",
    },
  },
  {
    userId: "#0013",
    propertyName: "Grand Hills Resort",
    type: "Tour",
    location: "Miami, USA",
    price: 4500,
    joinDate: "Jan 15, 2023",
    status: "Booked",
    image: b3,
    rating: 4.8,
    tourDetails: {
      duration: "5 days",
      groupSize: "10 people",
      inclusive: "Hotel + Beach Access",
      location: "Miami, USA",
    },
  },
  {
    userId: "#0014",
    propertyName: "Sunset Villa",
    type: "Tour",
    location: "Hawaii, USA",
    price: 5200,
    joinDate: "April 10, 2023",
    status: "Available",
    image: b4,
    rating: 4.9,
    tourDetails: {
      duration: "6 days",
      groupSize: "15 people",
      inclusive: "Hotel + All Meals",
      location: "Hawaii, USA",
    },
  },
  {
    userId: "#0015",
    propertyName: "Luxury Escape",
    type: "Tour",
    location: "Paris, France",
    price: 4500,
    joinDate: "Feb 7, 2023",
    status: "Available",
    image: b1,
    rating: 4.5,
    tourDetails: {
      duration: "7 days",
      groupSize: "20 people",
      inclusive: "Flights + Hotel + Meals",
      location: "Paris, France",
    },
  },
  {
    userId: "#0016",
    propertyName: "Oceanview Paradise",
    type: "Apartment",
    location: "Maldives",
    price: 6500,
    joinDate: "May 1, 2022",
    status: "Booked",
    image: b5,
    rating: 4.8,
    tourDetails: {
      duration: "5 days",
      groupSize: "8 people",
      inclusive: "Hotel + Spa Access",
      location: "Maldives",
    },
  },
  {
    userId: "#0017",
    propertyName: "Mountain Retreat",
    type: "Hotel",
    location: "Colorado, USA",
    price: 3500,
    joinDate: "Oct 13, 2023",
    status: "Available",
    image: b1,
    rating: 4.7,
    tourDetails: {
      duration: "4 days",
      groupSize: "12 people",
      inclusive: "Hotel + Meals",
      location: "Colorado, USA",
    },
  },
  {
    userId: "#0018",
    propertyName: "Tropical Getaway",
    type: "Tour",
    location: "Bora Bora",
    price: 7000,
    joinDate: "May 3, 2023",
    status: "Booked",
    image: b2,
    rating: 5.0,
    tourDetails: {
      duration: "10 days",
      groupSize: "25 people",
      inclusive: "Hotel + Flights + Meals",
      location: "Bora Bora",
    },
  },
  {
    userId: "#0019",
    propertyName: "Desert Oasis",
    type: "Apartment",
    location: "Dubai, UAE",
    price: 5000,
    joinDate: "Jan 22, 2024",
    status: "Available",
    image: b3,
    rating: 4.6,
    tourDetails: {
      duration: "6 days",
      groupSize: "10 people",
      inclusive: "Hotel + All Meals",
      location: "Dubai, UAE",
    },
  },
  {
    userId: "#0020",
    propertyName: "Snowy Peaks Lodge",
    type: "Hotel",
    location: "Aspen, USA",
    price: 4500,
    joinDate: "Dec 5, 2023",
    status: "Booked",
    image: b4,
    rating: 4.9,
    tourDetails: {
      duration: "5 days",
      groupSize: "8 people",
      inclusive: "Hotel + Ski Pass",
      location: "Aspen, USA",
    },
  },
];
