export const reviewData = [
  {
    userName: "Stephanie Shamasy",
    userImage: "https://i.pravatar.cc/150?img=1",
    reservation: "Grand Vintz Hotel",
    propertyImage: "https://source.unsplash.com/featured/?hotel",
    review: "Loved the hotel's ambiance and service. Totally recommend!",
    rating: 4.9,
    status: "Approved",
    action: "View details",
  },
  {
    userName: "David Ryan",
    userImage: "https://i.pravatar.cc/150?img=2",
    reservation: "Ocean Dream Resort",
    propertyImage: "https://source.unsplash.com/featured/?resort",
    review:
      "The hotel had a great location and friendly staff, but rooms were small.",
    rating: 4.3,
    status: "Approved",
    action: "View details",
  },
  {
    userName: "Jameson Philips",
    userImage: "https://i.pravatar.cc/150?img=3",
    reservation: "Elite City Residences",
    propertyImage: "https://source.unsplash.com/featured/?apartment",
    review: "Our stay was pleasant, with clean rooms and excellent service.",
    rating: 4.7,
    status: "Approved",
    action: "View details",
  },
  {
    userName: "Dennis Colin",
    userImage: "https://i.pravatar.cc/150?img=4",
    reservation: "Skyline Inn",
    propertyImage: "https://source.unsplash.com/featured/?inn",
    review:
      "The hotel was clean, comfortable, and the breakfast was delicious.",
    rating: 4.1,
    status: "Approved",
    action: "View details",
  },
  {
    userName: "Katie Dins",
    userImage: "https://i.pravatar.cc/150?img=5",
    reservation: "Urban Stay Apartments",
    propertyImage: "https://source.unsplash.com/featured/?urban",
    review: "The apartment was nice, but noisy at night.",
    rating: 3.6,
    status: "Pending",
    action: "⏳",
  },
  {
    userName: "Elisa Blackwell",
    userImage: "https://i.pravatar.cc/150?img=6",
    reservation: "Summit Loft Suites",
    propertyImage: "https://source.unsplash.com/featured/?loft",
    review: "The room was spacious and clean, but the service was average.",
    rating: 2.9,
    status: "Rejected",
    action: "❌",
  },
  {
    userName: "James Hall",
    userImage: "https://i.pravatar.cc/150?img=7",
    reservation: "Trip to Italy",
    propertyImage: "https://source.unsplash.com/featured/?italy",
    review:
      "This tour was smooth and organized well. The guide was knowledgeable.",
    rating: 4.8,
    status: "Approved",
    action: "View details",
  },
  {
    userName: "Clara Benson",
    userImage: "https://i.pravatar.cc/150?img=8",
    reservation: "Golden Gate Hotel",
    propertyImage: "https://source.unsplash.com/featured/?golden-gate",
    review: "Amazing view and comfortable stay.",
    rating: 4.5,
    status: "Approved",
    action: "View details",
  },
  {
    userName: "Henry Mills",
    userImage: "https://i.pravatar.cc/150?img=9",
    reservation: "Palm Beach Villas",
    propertyImage: "https://source.unsplash.com/featured/?beach-villa",
    review: "Spacious rooms but poor WiFi connectivity.",
    rating: 3.8,
    status: "Pending",
    action: "⏳",
  },
  {
    userName: "Nina Gomez",
    userImage: "https://i.pravatar.cc/150?img=10",
    reservation: "Sunset Paradise Inn",
    propertyImage: "https://source.unsplash.com/featured/?sunset",
    review: "Loved the sunsets and room service.",
    rating: 4.6,
    status: "Approved",
    action: "View details",
  },
  {
    userName: "Oliver Trent",
    userImage: "https://i.pravatar.cc/150?img=11",
    reservation: "Maple Stay Suites",
    propertyImage: "https://source.unsplash.com/featured/?suites",
    review: "Decent stay, value for money.",
    rating: 4.0,
    status: "Approved",
    action: "View details",
  },
  {
    userName: "Sophia Brooks",
    userImage: "https://i.pravatar.cc/150?img=12",
    reservation: "Dreamline Motel",
    propertyImage: "https://source.unsplash.com/featured/?motel",
    review: "Basic facilities, great staff.",
    rating: 3.9,
    status: "Pending",
    action: "⏳",
  },
  {
    userName: "Leo Harrison",
    userImage: "https://i.pravatar.cc/150?img=13",
    reservation: "Blue Lagoon Inn",
    propertyImage: "https://source.unsplash.com/featured/?lagoon",
    review: "Had a peaceful and relaxing experience.",
    rating: 4.4,
    status: "Approved",
    action: "View details",
  },
  {
    userName: "Isla Raymond",
    userImage: "https://i.pravatar.cc/150?img=14",
    reservation: "Coral View Resort",
    propertyImage: "https://source.unsplash.com/featured/?coral",
    review: "View was great but maintenance needs work.",
    rating: 3.5,
    status: "Rejected",
    action: "❌",
  },
  {
    userName: "Mason Clarke",
    userImage: "https://i.pravatar.cc/150?img=15",
    reservation: "Snowfall Cabins",
    propertyImage: "https://source.unsplash.com/featured/?cabin",
    review: "Perfect for a winter escape. Loved it!",
    rating: 4.9,
    status: "Approved",
    action: "View details",
  },
  {
    userName: "Emily Stone",
    userImage: "https://i.pravatar.cc/150?img=16",
    reservation: "Cozy Corner Lodge",
    propertyImage: "https://source.unsplash.com/featured/?lodge",
    review: "It was cozy and the staff was lovely.",
    rating: 4.3,
    status: "Approved",
    action: "View details",
  },
  {
    userName: "Logan Smith",
    userImage: "https://i.pravatar.cc/150?img=17",
    reservation: "Cityview Apartments",
    propertyImage: "https://source.unsplash.com/featured/?cityview",
    review: "Modern interiors but check-in was delayed.",
    rating: 3.7,
    status: "Pending",
    action: "⏳",
  },
  {
    userName: "Ava Knight",
    userImage: "https://i.pravatar.cc/150?img=18",
    reservation: "Heritage Inn",
    propertyImage: "https://source.unsplash.com/featured/?heritage",
    review: "A wonderful mix of history and comfort.",
    rating: 4.6,
    status: "Approved",
    action: "View details",
  },
  {
    userName: "Liam Turner",
    userImage: "https://i.pravatar.cc/150?img=19",
    reservation: "Desert Bloom Hotel",
    propertyImage: "https://source.unsplash.com/featured/?desert",
    review: "Very hot but rooms had great AC.",
    rating: 4.1,
    status: "Approved",
    action: "View details",
  },
  {
    userName: "Mila Grant",
    userImage: "https://i.pravatar.cc/150?img=20",
    reservation: "Mountain Edge Chalet",
    propertyImage: "https://source.unsplash.com/featured/?mountain",
    review: "Quiet, scenic, and very clean. Would visit again!",
    rating: 4.8,
    status: "Approved",
    action: "View details",
  },
];
