import t1 from "@/public/toure/t1.jpg";
import t2 from "@/public/toure/t2.jpg";
import t3 from "@/public/toure/t3.jpg";
import t4 from "@/public/toure/t4.jpg";
import t5 from "@/public/toure/t5.jpg";
import t6 from "@/public/toure/t6.jpg";

export const toursData = [
  {
    category: "Hotel",
    tag: "Featured",
    image: t1,
    location: "Beijing, China",
    flag: "/images/flags/cn.png",
    title: "Unforgettable China: A Journey Through Time and Tradition",
    tourSlug: "unforgettable-china",
    rating: 4.5,
    reviews: 112,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 1,
    price: "8590",
    capacity: 4,
    size: "950",
    duration: 6,
    groupSize: 12,
  },
  {
    category: "Tour",
    tag: "Featured",
    image: t2,
    location: "Bali, Indonesia",
    flag: "/images/flags/id.png",
    title: "Indonesia Unveiled: Small Group Journey",
    tourSlug: "indonesia-journey",
    rating: 4.3,
    reviews: 76,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: false,
    breakfast: true,
    bed: 1,
    bath: 1,
    price: "4999",
    capacity: 2,
    size: "600",
    duration: 4,
    groupSize: 4,
  },
  {
    category: "Hotel",
    image: t3,
    tag: "Featured",
    location: "Rome, Italy",
    flag: "/images/flags/it.png",
    title: "Italy Awaits: A Journey Through History and Culture",
    tourSlug: "italy-journey",
    rating: 4.7,
    reviews: 142,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 2,
    price: "4999",
    capacity: 4,
    size: "1100",
    duration: 2,
    groupSize: 8,
  },
  {
    category: "Tour",
    image: t4,
    tag: "Featured",
    location: "Kathmandu, Nepal",
    flag: "/images/flags/np.png",
    title: "Kathmandu Wonders Experience",
    tourSlug: "kathmandu-wonders",
    rating: 4.2,
    reviews: 65,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 1,
    bath: 1,
    price: "4999",
    capacity: 2,
    size: "800",
    duration: 4,
    groupSize: 8,
  },
  {
    category: "Apartments",
    image: t5,
    tag: "Featured",
    location: "Abu Dhabi, UAE",
    flag: "/images/flags/ae.png",
    title: "Abu Dhabi Hotel",
    tourSlug: "abu-dhabi-hotel",
    rating: 4.8,
    reviews: 85,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 2,
    price: "488",
    capacity: 6,
    size: "1200",
    duration: 5,
    groupSize: 15,
  },
  {
    category: "Resort",
    image: t6,
    tag: "Featured",
    location: "Male, Maldives",
    flag: "/images/flags/mv.png",
    title: "Maldives Island Getaway",
    tourSlug: "maldives-getaway",
    rating: 4.9,
    reviews: 190,
    cancellation: "Cancel within 48H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 1,
    bath: 1,
    price: "9999",
    capacity: 2,
    size: "900",
    duration: 4,
    groupSize: 6,
  },
  {
    category: "Hotel",
    image: t4,
    tag: "Featured",
    location: "Paris, France",
    flag: "/images/flags/fr.png",
    title: "Romantic Paris Escape",
    tourSlug: "paris-escape",
    rating: 4.6,
    reviews: 132,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 1,
    bath: 1,
    price: "7200",
    capacity: 2,
    size: "850",
    duration: 3,
    groupSize: 8,
  },
  {
    category: "Apartment",
    image: t2,
    tag: "Featured",
    location: "Tokyo, Japan",
    flag: "/images/flags/jp.png",
    title: "Tokyo Urban Stay",
    tourSlug: "tokyo-urban",
    rating: 4.4,
    reviews: 98,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: false,
    bed: 2,
    bath: 1,
    price: "5300",
    capacity: 4,
    size: "980",
    duration: 4,
    groupSize: 8,
  },
  {
    category: "Hotel",
    image: t6,
    tag: "Featured",
    location: "New York, USA",
    flag: "/images/flags/us.png",
    title: "Manhattan Luxury Stay",
    tourSlug: "manhattan-luxury",
    rating: 4.9,
    reviews: 210,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 3,
    bath: 2,
    price: "8999",
    capacity: 6,
    size: "1500",
    duration: 5,
    groupSize: 11,
  },
  {
    category: "Resort",
    image: t1,
    tag: "Featured",
    location: "Phuket, Thailand",
    flag: "/images/flags/th.png",
    title: "Phuket Tropical Retreat",
    tourSlug: "phuket-retreat",
    rating: 4.5,
    reviews: 109,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 2,
    price: "6800",
    capacity: 4,
    size: "1050",
    duration: 3,
    groupSize: 6,
  },
  {
    category: "Hotel",
    image: t2,
    tag: "Featured",
    location: "Sydney, Australia",
    flag: "/images/flags/au.png",
    title: "Harbourview Stay Sydney",
    tourSlug: "sydney-harbourview",
    rating: 4.3,
    reviews: 73,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: false,
    bed: 2,
    bath: 1,
    price: "5500",
    capacity: 4,
    size: "920",
    duration: 2,
    groupSize: 8,
  },
  {
    category: "Hotel",
    image: t3,
    tag: "Featured",
    location: "Cairo, Egypt",
    flag: "/images/flags/eg.png",
    title: "Mysteries of Cairo Tour",
    tourSlug: "cairo-tour",
    rating: 4.1,
    reviews: 55,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 1,
    bath: 1,
    price: "4700",
    capacity: 2,
    size: "700",
    duration: 4,
    groupSize: 10,
  },
  {
    category: "Apartment",
    image: t4,
    tag: "Featured",
    location: "Berlin, Germany",
    flag: "/images/flags/de.png",
    title: "Modern Berlin Stay",
    tourSlug: "berlin-modern",
    rating: 4.4,
    reviews: 67,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: false,
    bed: 2,
    bath: 1,
    price: "5100",
    capacity: 4,
    size: "1000",
    duration: 7,
    groupSize: 15,
  },
  {
    category: "Tour",
    image: t5,
    tag: "Featured",
    location: "Istanbul, Turkey",
    flag: "/images/flags/tr.png",
    title: "Istanbul Culture Tour",
    tourSlug: "istanbul-culture",
    rating: 4.5,
    reviews: 89,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 1,
    bath: 1,
    price: "4990",
    capacity: 2,
    size: "800",
    duration: 4,
    groupSize: 8,
  },
  {
    category: "Hotel",
    image: t6,
    tag: "Featured",
    location: "Seoul, South Korea",
    flag: "/images/flags/kr.png",
    title: "Seoul City Lights Stay",
    tourSlug: "seoul-lights",
    rating: 4.6,
    reviews: 101,
    cancellation: "Cancel within 24H",
    wifi: true,
    tv: true,
    breakfast: true,
    bed: 2,
    bath: 2,
    price: "5900",
    capacity: 4,
    size: "1100",
    duration: 3,
    groupSize: 12,
  },
];
